# Starter pipeline
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'Harness NG REST API'
    method: 'POST'
    body: |
      pipeline:
        identifier: STO_Stage_Demo
        properties:
          ci:
            codebase:
              build:
                spec:
                  branch: master
                type: branch
    waitForCompletion: 'false'
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'Harness NG REST API'
    method: 'POST'
    body: |
      pipeline:
        identifier: STO_Stage_Demo
        properties:
          ci:
            codebase:
              build:
                spec:
                  branch: master
                type: branch
    waitForCompletion: 'false'
